server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:ms_user
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update
