server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:ms_email
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update

  rabbitmq:
    addresses: amqps://ufdasfgg:GEytoc_UqquNcwrzqEnP6gwhAl5zjgMX@beaver.rmq.cloudamqp.com/ufdasfgg

broker:
  queue:
    email:
      name: default.email


# amqps://ufdasfgg:GEytoc_UqquNcwrzqEnP6gwhAl5zjgMX@beaver.rmq.cloudamqp.com/ufdasfgg